# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repository:
    description: 'Repository name with owner. For example, owner/repo'
    default: ${{ github.repository }}
  branch:
    description: 'Git branch to use in links on Confluence'
    default: 'master'
  confluence_url:
    description: 'URL to your Confluence hosting (with /wiki at the end)'
    required: true
  confluence_username:
    description: 'Username of the token user'
    required: true
  confluence_token:
    description: 'Token for the user'
    required: true
  confluence_space:
    description: 'Space on Confluence to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
